# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/grayside"
weight = 25
[social.params]
icon = "brand-github"

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://hachyderm.io/@grayside"
weight = 50
[social.params]
icon = "brand-mastodon"

[[social]]
identifier = "rss"
name = "RSS Feed"
url = "/index.xml"
weight = 100
[[social.params]]
icon = "rss"